language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

env:
  - TRAVIS_NODE_VERSION="8"
  - MYSQL_TEST_DATABASE="yii2_basic_tests"
  - MYSQL_USER="travis"
  - MYSQL_PASSWORD=""

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - mysql -e 'CREATE DATABASE $MYSQL_TEST_DATABASE;'

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g bower gulp
  - npm install
  - bower install
  - npm run build
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php
script:
  - |
    php -S localhost:8080 -t web > /dev/null 2>&1 &
    vendor/bin/codecept run