#!/bin/bash

mysql -uroot -p${MYSQL_ROOT_PASSWORD} <<MYSQL_SCRIPT
CREATE DATABASE IF NOT EXISTS ${MYSQL_TEST_DATABASE};
GRANT ALL ON ${MYSQL_TEST_DATABASE}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
MYSQL_SCRIPT

echo "Created database ${MYSQL_TEST_DATABASE}"